### ISSUE TITLE
When handling single file compiling, the compilation fail

### ISSUE THREAD

**Issue by jimthunderbird** [jimthunderbird/php-to-c-extension#6]
When doing the following:
php build_extension.php [file to be converted to extension]
The screen is blank and the compilation  process is not working.

**Comment by azcpavel** [comment]
Error: PHP Parser Error: Syntax error, unexpected '<', expecting T_STRING on line 3

File Name#
Dummy.php

Code#
<?php
namespace Dummy;
class Hello 
{
  public function say()
  {
    echo "hello";
  }
}

Debug Output#
$sourceFileContent = <?php namespace Dummy; class <scalar:null/> { public function say() { echo 
 "hello"; } }
